#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v18
# autospec commit: eaa4f711da30
#
Name     : pavucontrol
Version  : 5.0
Release  : 12
URL      : https://www.freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-5.0.tar.xz
Source0  : https://www.freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-5.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: pavucontrol-bin = %{version}-%{release}
Requires: pavucontrol-data = %{version}-%{release}
Requires: pavucontrol-license = %{version}-%{release}
Requires: pavucontrol-locales = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : libsigc++-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gtkmm-3.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-mainloop-glib)
BuildRequires : pkgconfig(sigc++-2.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PulseAudio Volume Control 5.0
* [1]License
* [2]News
* [3]Overview
* [4]Current Status
* [5]Documentation
* [6]Requirements
* [7]Installation
* [8]Download
* [9]Bug Reports
* [10]Contributing Code
* [11]Contributing Translations

%package bin
Summary: bin components for the pavucontrol package.
Group: Binaries
Requires: pavucontrol-data = %{version}-%{release}
Requires: pavucontrol-license = %{version}-%{release}

%description bin
bin components for the pavucontrol package.


%package data
Summary: data components for the pavucontrol package.
Group: Data

%description data
data components for the pavucontrol package.


%package doc
Summary: doc components for the pavucontrol package.
Group: Documentation

%description doc
doc components for the pavucontrol package.


%package license
Summary: license components for the pavucontrol package.
Group: Default

%description license
license components for the pavucontrol package.


%package locales
Summary: locales components for the pavucontrol package.
Group: Default

%description locales
locales components for the pavucontrol package.


%prep
%setup -q -n pavucontrol-5.0
cd %{_builddir}/pavucontrol-5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722967265
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1722967265
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pavucontrol
cp %{_builddir}/pavucontrol-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pavucontrol/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
export GOAMD64=v2
GOAMD64=v2
%make_install
%find_lang pavucontrol

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pavucontrol

%files data
%defattr(-,root,root,-)
/usr/share/applications/pavucontrol.desktop
/usr/share/pavucontrol/pavucontrol.glade

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/pavucontrol/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pavucontrol/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files locales -f pavucontrol.lang
%defattr(-,root,root,-)

